# Generated by Django 5.1.4 on 2025-06-04 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("train_station", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journeys",
                to="train_station.route",
            ),
        ),
        migrations.AddField(
            model_name="routestation",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_stations",
                to="train_station.route",
            ),
        ),
        migrations.AddField(
            model_name="journeystation",
            name="route_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journey_stations",
                to="train_station.routestation",
            ),
        ),
        migrations.AddField(
            model_name="routestation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="route_stations",
                to="train_station.station",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_routes",
                to="train_station.station",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_routes",
                to="train_station.station",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="arrival_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival_tickets",
                to="train_station.station",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="departure_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_tickets",
                to="train_station.station",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tickets",
                to="train_station.journey",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="train_station.order",
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="train",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journeys",
                to="train_station.train",
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="train_station.traintype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journeystation",
            unique_together={("journey", "route_station")},
        ),
        migrations.AlterUniqueTogether(
            name="routestation",
            unique_together={("route", "station")},
        ),
    ]
