# Generated by Django 4.2.14 on 2024-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="duration_list",
            field=models.CharField(
                default=[0, 0, 0],
                help_text="list of all differences in date between departures and arrivals.\nExample: [0, 0, 1]",
                max_length=256,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="route",
            name="departure_list",
            field=models.CharField(
                help_text="list of all departures.\nExample: [[10, 23], [17,21], [19,13]]",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="source_arrival_list",
            field=models.CharField(
                help_text="list of all arrivals.\nExample: [[20, 23], [23,21], [2,13]]",
                max_length=256,
            ),
        ),
    ]
