# Generated by Django 4.2.14 on 2024-09-08 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "train_station",
            "0002_route_duration_list_alter_route_departure_list_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="departure_list",
        ),
        migrations.RemoveField(
            model_name="route",
            name="duration_list",
        ),
        migrations.RemoveField(
            model_name="route",
            name="source_arrival_list",
        ),
        migrations.AddField(
            model_name="journey",
            name="arrival_time",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="journey",
            name="departure_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="car",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
