# Generated by Django 5.1.4 on 2025-06-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["name"]},
        ),
    ]
