# Generated by Django 5.1.4 on 2025-06-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["departure_time"]},
        ),
        migrations.RemoveField(
            model_name="journey",
            name="route_journey_number",
        ),
    ]
