# Generated by Django 4.2.14 on 2024-09-08 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0003_remove_route_departure_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="route_journey_number",
            field=models.PositiveSmallIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
    ]
