# Generated by Django 5.1.4 on 2025-06-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0003_alter_journey_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="computed_arrival_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="computed_departure_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
