# Generated by Django 5.1.4 on 2025-07-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("train_station", "0004_ticket_computed_arrival_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routestation",
            name="route_ordinal_station_number",
        ),
    ]
