# Generated by Django 5.1.4 on 2025-04-01 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_station', '0004_journey_route_journey_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journey',
            options={'ordering': ['route_journey_number']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='no_journey_month_days',
        ),
        migrations.RemoveField(
            model_name='route',
            name='no_journey_week_days',
        ),
        migrations.AddField(
            model_name='journey',
            name='no_journey_month_days',
            field=models.CharField(blank=True, help_text='list of days. Example [12, 18, 31]', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='no_journey_week_days',
            field=models.CharField(blank=True, help_text='list of week days. Example [0, 4]', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='intermediatestation',
            name='arrival_list',
            field=models.CharField(help_text='list of all arrivals in format [[journey#1_hours, journey#1_minutes], [journey#2_hours, journey#2_minutes], [journey#3_hours, journey#3_minutes]]Example: [[17,21], [19,30], [23,12]', max_length=256),
        ),
        migrations.AlterField(
            model_name='intermediatestation',
            name='departure_list',
            field=models.CharField(help_text='list of all departures in format [[journey#1_hours, journey#1_minutes], [journey#2_hours, journey#2_minutes], [journey#3_hours, journey#3_minutes]]Example: [[20,21], [22,30], [2,12]', max_length=256),
        ),
        migrations.AlterField(
            model_name='journey',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journey',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
