# Generated by Django 5.1.4 on 2025-04-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_station', '0005_alter_journey_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediatestation',
            name='route',
        ),
        migrations.AddField(
            model_name='intermediatestation',
            name='journey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='journey_intermediate_stations', to='train_station.journey'),
            preserve_default=False,
        ),
    ]
