# Generated by Django 5.1.4 on 2025-04-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_station', '0006_remove_intermediatestation_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='no_journey_month_days',
            field=models.JSONField(blank=True, help_text='list of days. Example [12, 18, 31]', null=True),
        ),
        migrations.AlterField(
            model_name='journey',
            name='no_journey_week_days',
            field=models.JSONField(blank=True, help_text='list of week days. Example [0, 4]', null=True),
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_ordinal_station_number', models.PositiveSmallIntegerField(help_text='Ordinal number from route source')),
                ('route_distance_already_passed_km', models.PositiveSmallIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stations', to='train_station.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stations', to='train_station.station')),
            ],
            options={
                'unique_together': {('route', 'station')},
            },
        ),
        migrations.CreateModel(
            name='JourneyStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_stations', to='train_station.journey')),
                ('route_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_stations', to='train_station.routestation')),
            ],
            options={
                'unique_together': {('journey', 'route_station')},
            },
        ),
        migrations.DeleteModel(
            name='IntermediateStation',
        ),
    ]
